name: Release Obsidian plugin
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Install Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3.3.1
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Check if esbuild.config.ts exists
        id: check-config
        run: |
          if [ -f "esbuild.config.ts" ]; then
            echo "esbuild.config.ts found."
            echo "::set-output name=config-found::true"
          else
            echo "esbuild.config.ts not found."
            echo "::set-output name=config-found::false"
            ls -a
          fi
      - name: Build with tsx
        if: steps.check-config.outputs.config-found == 'true'
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            main.js manifest.json
